export const getCars = () => [
  {
    id: 1,
    name: "Toyota Camry 2024",
    brand: "Toyota",
    model: "Camry",
    year: 2024,
    price: 28500,
    mileage: 15000,
    fuel: "Gasoline",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&h=400&fit=crop",
    category: "Sedan",
    condition: "New",
    titleStatus: "Clean Title",
    color: "White",
    engine: "2.5L 4-Cylinder",
    horsepower: 203,
    features: ["Bluetooth", "Backup Camera", "Apple CarPlay", "Android Auto", "Lane Keep Assist", "Adaptive Cruise Control", "Dual Zone Climate", "Wireless Charging"],
  },
  {
    id: 2,
    name: "BMW M5 Competition",
    brand: "BMW",
    model: "M5",
    year: 2023,
    price: 78000,
    mileage: 8500,
    fuel: "Gasoline",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&h=400&fit=crop",
    category: "Supercar",
    condition: "Used",
    titleStatus: "Clean Title",
    color: "Black",
    engine: "4.4L V8 Twin-Turbo",
    horsepower: 617,
    features: ["Leather Seats", "Panoramic Roof", "Harman Kardon Audio", "Heads-up Display", "Heated Steering Wheel", "Night Vision", "Soft Close Doors", "M Sport Package"],
  },
  {
    id: 3,
    name: "Ford F-150 Lariat",
    brand: "Ford",
    model: "F-150",
    year: 2024,
    price: 52000,
    mileage: 12000,
    fuel: "Hybrid",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=600&h=400&fit=crop",
    category: "Pickup",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Blue",
    engine: "3.5L PowerBoost Hybrid",
    horsepower: 430,
    features: ["4x4", "Tow Package", "Pro Power Onboard", "Adaptive Cruise", "360 Camera", "Tailgate Step", "Zone Lighting", "Max Recline Seats"],
  },
  {
    id: 4,
    name: "Mercedes-Benz EQS 580",
    brand: "Mercedes-Benz",
    model: "EQS",
    year: 2024,
    price: 95000,
    mileage: 3000,
    fuel: "Electric",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&h=400&fit=crop",
    category: "Sedan",
    condition: "New",
    titleStatus: "Rebuilt Title",
    color: "Silver",
    engine: "Dual Motor Electric",
    horsepower: 516,
    features: ["MBUX Hyperscreen", "Air Suspension", "Burmester Audio", "Executive Package", "Rear Seat Entertainment", "E-Active Body Control", "Augmented Reality Navigation", "OTA Updates"],
  },
  {
    id: 5,
    name: "Porsche 911 Turbo S",
    brand: "Porsche",
    model: "911",
    year: 2023,
    price: 225000,
    mileage: 5000,
    fuel: "Gasoline",
    transmission: "PDK",
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=600&h=400&fit=crop",
    category: "Supercar",
    condition: "Used",
    titleStatus: "Clean Title",
    color: "Grey",
    engine: "3.8L Twin-Turbo Flat-6",
    horsepower: 640,
    features: ["Sport Chrono", "Ceramic Brakes", "Sport Exhaust", "Launch Control", "PASM Suspension", "Rear Axle Steering", "Bose Surround Sound", "Sport Seats Plus"],
  },
  {
    id: 6,
    name: "Honda CR-V Hybrid",
    brand: "Honda",
    model: "CR-V",
    year: 2024,
    price: 33500,
    mileage: 8000,
    fuel: "Hybrid",
    transmission: "CVT",
    image: "https://picsum.photos/seed/hondacrv/600/400",
    category: "SUV",
    condition: "New",
    titleStatus: "Rebuilt Title",
    color: "Red",
    engine: "2.0L Hybrid",
    horsepower: 204,
    features: ["Honda Sensing", "Wireless Charging", "Google Built-in", "AWD", "Blind Spot Monitor", "Heated Seats", "Power Liftgate", "Remote Start"],
  },
  {
    id: 7,
    name: "Chevrolet Corvette Z06",
    brand: "Chevrolet",
    model: "Corvette",
    year: 2024,
    price: 115000,
    mileage: 2000,
    fuel: "Gasoline",
    transmission: "Dual-Clutch",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&h=400&fit=crop",
    category: "Supercar",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Orange",
    engine: "5.5L Flat-Plane V8",
    horsepower: 670,
    features: ["Magnetic Ride Control", "Performance Data Recorder", "Carbon Fiber", "Z07 Package", "Performance Traction Management", "Electronic Limited Slip", "Head-Up Display", "Performance Exhaust"],
  },
  {
    id: 8,
    name: "Lexus RX 500h",
    brand: "Lexus",
    model: "RX",
    year: 2024,
    price: 62000,
    mileage: 6000,
    fuel: "Hybrid",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=600&h=400&fit=crop",
    category: "SUV",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Black",
    engine: "2.4L Turbo Hybrid",
    horsepower: 366,
    features: ["Mark Levinson Audio", "Panoramic Roof", "Advanced Drive", "AVS Suspension", "Digital Rearview Mirror", "Kiriko Glass Interior", "Hands-Free Power Liftgate", "Intuitive Park Assist"],
  },
  {
    id: 9,
    name: "Tesla Model 3 Performance",
    brand: "Tesla",
    model: "Model 3",
    year: 2024,
    price: 52000,
    mileage: 1000,
    fuel: "Electric",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=600&h=400&fit=crop",
    category: "Sedan",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Red",
    engine: "Dual Motor Electric",
    horsepower: 510,
    features: ["Autopilot", "15\" Touchscreen", "Premium Audio", "Glass Roof", "Heated Seats", "Over-the-Air Updates", "Track Mode", "Carbon Fiber Spoiler"],
  },
  {
    id: 10,
    name: "Audi RS e-tron GT",
    brand: "Audi",
    model: "RS e-tron GT",
    year: 2024,
    price: 145000,
    mileage: 2500,
    fuel: "Electric",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=600&h=400&fit=crop",
    category: "Supercar",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Grey",
    engine: "Dual Motor Electric",
    horsepower: 637,
    features: ["Matrix LED Headlights", "Bang & Olufsen Audio", "Air Suspension", "Quattro AWD", "Rear Axle Steering", "Virtual Cockpit Plus", "Panoramic Roof", "Fast Charging"],
  },
  {
    id: 11,
    name: "Jeep Wrangler Rubicon",
    brand: "Jeep",
    model: "Wrangler",
    year: 2024,
    price: 48000,
    mileage: 500,
    fuel: "Gasoline",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&h=400&fit=crop",
    category: "SUV",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Green",
    engine: "3.6L V6",
    horsepower: 285,
    features: ["4x4", "Locking Differials", "Disconnecting Sway Bar", "Rock Rails", "33\" All-Terrain Tires", "Removable Doors", "Sky One-Touch Roof", "Trail Rated Badge"],
  },
  {
    id: 12,
    name: "Range Rover Sport",
    brand: "Land Rover",
    model: "Range Rover Sport",
    year: 2024,
    price: 85000,
    mileage: 4000,
    fuel: "Hybrid",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1606220838315-056192d5e927?w=600&h=400&fit=crop",
    category: "SUV",
    condition: "New",
    titleStatus: "Clean Title",
    color: "White",
    engine: "3.0L Inline-6 Turbo",
    horsepower: 395,
    features: ["Terrain Response", "Meridian Audio", "Air Suspension", "Dynamic Response System", "Pixel LED Headlights", "Rear Seat Entertainment", "ClearSight Mirror", "Wade Sensing"],
  },
  {
    id: 13,
    name: "Mazda CX-5 Turbo",
    brand: "Mazda",
    model: "CX-5",
    year: 2024,
    price: 38000,
    mileage: 3000,
    fuel: "Gasoline",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&h=400&fit=crop",
    category: "SUV",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Blue",
    engine: "2.5L Turbo",
    horsepower: 256,
    features: ["AWD", "Bose Audio", "Head-Up Display", "360 Camera", "Heated Steering Wheel", "Wireless Charging", "Traffic Sign Recognition", "i-Activsense Safety"],
  },
  {
    id: 14,
    name: "Ram 1500 TRX",
    brand: "Ram",
    model: "1500 TRX",
    year: 2024,
    price: 82000,
    mileage: 1500,
    fuel: "Gasoline",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=600&h=400&fit=crop",
    category: "Pickup",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Black",
    engine: "6.2L Supercharged V8",
    horsepower: 702,
    features: ["Bilstein Shocks", "Launch Mode", "Harman Kardon Audio", "12\" Touchscreen", "Head-Up Display", "Bed Utility Group", "Off-Road Pages", "Adaptive Damping"],
  },
  {
    id: 15,
    name: "Genesis GV70",
    brand: "Genesis",
    model: "GV70",
    year: 2024,
    price: 55000,
    mileage: 2000,
    fuel: "Gasoline",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&h=400&fit=crop",
    category: "SUV",
    condition: "New",
    titleStatus: "Clean Title",
    color: "Silver",
    engine: "3.5L Twin-Turbo V6",
    horsepower: 375,
    features: ["Lexicon Audio", "Remote Smart Parking", "Highway Driving Assist II", "Nappa Leather", "Quilted Interior", "Fingerprint Authentication", "Digital Key", "Smart Posture Care"],
  },
  {
    id: 16,
    name: "Volkswagen ID.4 Pro",
    brand: "Volkswagen",
    model: "ID.4",
    year: 2024,
    price: 42000,
    mileage: 800,
    fuel: "Electric",
    transmission: "Automatic",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&h=400&fit=crop",
    category: "SUV",
    condition: "New",
    titleStatus: "Clean Title",
    color: "White",
    engine: "Single Motor Electric",
    horsepower: 282,
    features: ["IQ.Drive Assist", "Panoramic Roof", "Wireless Charging", "Heated Seats", "Travel Assist", "Augmented Reality HUD", "ID.Light", "DC Fast Charging"],
  },
];

export const getCarById = (id) => {
  const cars = getCars();
  return cars.find((car) => car.id === parseInt(id));
};

export const getFeaturedCars = () => {
  return getCars().filter((car) => car.condition === "New").slice(0, 12);
};

export const searchCars = (query) => {
  const cars = getCars();
  const lowerQuery = query.toLowerCase();
  return cars.filter(
    (car) =>
      car.name.toLowerCase().includes(lowerQuery) ||
      car.brand.toLowerCase().includes(lowerQuery) ||
      car.model.toLowerCase().includes(lowerQuery)
  );
};
